/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "TIA.h"
#include "VDAC_VG.h"
#include "isr_Crono.h"
#include "ADC_DelSig.h"
#include "Working_Electrode_aliases.h"
#include "Working_Electrode.h"
#include "AMux_Cur.h"
#include "IDAC_Calibration.h"
#include "Ext_Cap_Pin_aliases.h"
#include "Ext_Cap_Pin.h"
#include "Counter_Electrode_aliases.h"
#include "Counter_Electrode.h"
#include "DVDAC_SetV.h"
#include "isr_CV.h"
#include "Clock_PWM.h"
#include "PWM_isr.h"
#include "Opamp.h"
#include "AMux_Electrodes.h"
#include "Referenece_Electrode_aliases.h"
#include "Referenece_Electrode.h"
#include "UART.h"
#include "isr_RX.h"
#include "Pin_LED_aliases.h"
#include "Pin_LED.h"
#include "ADC_DelSig_Ext_CP_Clk.h"
#include "ADC_DelSig_IRQ.h"
#include "ADC_DelSig_theACLK.h"
#include "DVDAC_SetV_DMA_dma.h"
#include "DVDAC_SetV_VDAC8.h"
#include "DVDAC_SetV_IntClock.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

